Symfony/Baskel/src/Produits/ProduitsBundle/Entity/Produits.php
<?php

namespace Produits\ProduitsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * Produits
 *
 * @ORM\Table(name="produits")
 * @ORM\Entity(repositoryClass="Produits\ProduitsBundle\Repository\ProduitsRepository")
 */
class Produits
{
    /**
     * @var int
     *
     * @ORM\Column(name="ref_p", type="integer")
     * @ORM\Id
     * @Assert\Length(min = 3, minMessage = "La reference doit contenir au moins 6 chiffres", max=6 ,maxMessage = "La reference doit contenir au plus 6 chiffres")
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $ref_p;

    /**
     * @var string
     *
     * @ORM\Column(name="nom_p", type="string", length=255)
     * @Assert\Length(min = 2, minMessage = "Le nom doit contenir au moins 2 caractères.")
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $nomP;

    /**
     * @var string
     *
     * @ORM\Column(name="genre_p", type="string", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $genreP;

    /**
     * @var array
     *
     * @ORM\Column(name="couleur_p", type="json_array", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $couleurP;

    /**
     * @var int
     *
     * @ORM\Column(name="quantite_p", type="integer")
     * @Assert\GreaterThanOrEqual(
     *     value = 0,
     *     message="Quantite ne peut pas etre négative."
     * )
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $quantiteP;

    /**
     * @var float
     *
     * @ORM\Column(name="prix_p", type="float")
     * * @Assert\GreaterThan(
     *     value = 0,
     *     message="Prix ne peut pas etre négative ou nul."
     * )
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $prixP;

    /**
     * @var string
     *
     * @ORM\Column(name="marque_p", type="string", length=255)
     * @Assert\Length(min = 2, minMessage = "Le nom de la marque doit contenir au moins 6 caractères.")
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $marqueP;


    /**
     * @var
     * @ORM\ManyToOne(targetEntity="Categories")
     * @ORM\JoinColumn(name="ref_c",referencedColumnName="ref_c",nullable=false)
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $ref_c;


    /**
     * @var text
     *
     * @ORM\Column(name="description", type="text", length=255)
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $description;



    /**
     * @var float
     *
     * @ORM\Column(name="solde", type="float",nullable=true)
     * @Assert\Range(
     *     min=0,
     *     max = 100,
     *     maxMessage="Remise ne peut pas dépasser 100.",
     *     minMessage="Remise ne peut pas être négative."
     * )
     */
    private $solde=0;

    /**
     * @var int
     *
     * @ORM\Column(name="rating_p", type="integer",nullable=true)
     * @Assert\GreaterThanOrEqual(
     *     value = 0,
     *     message="Quantite ne peut pas etre négative."
     * )
     * @Assert\NotBlank(message="Veuillez remplir ce champ!")
     */
    private $rating = 0;

    /**
     * @return int
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @param int $rating
     */
    public function setRating($rating)
    {
        $this->rating = $rating;
    }

    /**
     * @return float
     */
    public function getSolde()
    {
        return $this->solde;
    }

    /**
     * @param float $solde
     */
    public function setSolde($solde)
    {
        $this->solde = $solde;
    }






















    /**
     * @param int $ref_p
     */
    public function setRefP($ref_p)
    {
        $this -> ref_p = $ref_p;
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getRefP()
    {
        return $this->ref_p;
    }

    /**
     * Set nomP
     *
     * @param string $nomP
     *
     * @return Produits
     */
    public function setNomP($nomP)
    {
        $this->nomP = $nomP;

        return $this;
    }

    /**
     * Get nomP
     *
     * @return string
     */
    public function getNomP()
    {
        return $this->nomP;
    }

    /**
     * Set genreP
     *
     * @param string $genreP
     *
     * @return Produits
     */
    public function setGenreP($genreP)
    {
        $this->genreP = $genreP;

        return $this;
    }

    /**
     * Get genreP
     *
     * @return string
     */
    public function getGenreP()
    {
        return $this->genreP;
    }

    /**
     * Set couleurP
     *
     * @param string $couleurP
     *
     * @return Produits
     */
    public function setCouleurP($couleurP)
    {
        $this->couleurP = $couleurP;

        return $this;
    }

    /**
     * Get couleurP
     *
     * @return string
     */
    public function getCouleurP()
    {
        return $this->couleurP;
    }

    /**
     * Set quantiteP
     *
     * @param integer $quantiteP
     *
     * @return Produits
     */
    public function setQuantiteP($quantiteP)
    {
        $this->quantiteP = $quantiteP;

        return $this;
    }

    /**
     * Get quantiteP
     *
     * @return int
     */
    public function getQuantiteP()
    {
        return $this->quantiteP;
    }

    /**
     * Set prixP
     *
     * @param float $prixP
     *
     * @return Produits
     */
    public function setPrixP($prixP)
    {
        $this->prixP = $prixP;

        return $this;
    }

    /**
     * Get prixP
     *
     * @return float
     */
    public function getPrixP()
    {
        return $this->prixP;
    }

    /**
     * Set marqueP
     *
     * @param string $marqueP
     *
     * @return Produits
     */
    public function setMarqueP($marqueP)
    {
        $this->marqueP = $marqueP;

        return $this;
    }

    /**
     * Get marqueP
     *
     * @return string
     */
    public function getMarqueP()
    {
        return $this->marqueP;
    }

    /**
     * @return mixed
     */
    public function getRefC()
    {
        return $this -> ref_c;
    }



    /**
     * @param mixed $ref_c
     */
    public function setRefC($ref_c)
    {
        $this -> ref_c = $ref_c;
    }

    /**
     * @return text
     */
    public function getDescription()
    {
        return $this -> description;
    }

    /**
     * @param text $description
     */
    public function setDescription($description)
    {
        $this -> description = $description;
    }

















    /**
     * @var string
     * @Assert\NotBlank(message="Upload your image")
     * @Assert\Image()
     * @ORM\Column(name="image",type="string" ,length=255)
     */
    private $image;

    /**
     * @return string
     */
    public function getImage()
    {
        return $this -> image;
    }

    /**
     * @param string $image
     */
    public function setImage($image)
    {
        $this -> image = $image;
    }






}

Symfony/Baskel/src/Produits/ProduitsBundle/Controller/ProduitsController.php
<?php

namespace Produits\ProduitsBundle\Controller;

use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use mysql_xdevapi\Session;
use Produits\ProduitsBundle\Entity\Categories;
use Produits\ProduitsBundle\Entity\Mail;
use Produits\ProduitsBundle\Entity\Produits;
use Produits\ProduitsBundle\Entity\Rating;
use Produits\ProduitsBundle\Entity\User;
use Produits\ProduitsBundle\Entity\Wishlist;
use Produits\ProduitsBundle\Form\CategoriesType;
use Produits\ProduitsBundle\Form\MailType;
use Produits\ProduitsBundle\Form\ModifierSoldeType;
use Produits\ProduitsBundle\Form\ProduitsModifType;
use Produits\ProduitsBundle\Form\ProduitsType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Produits\ProduitsBundle\Repository\WishlistRepository;
use Swift_Message;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;



class ProduitsController extends Controller
{
    public function shopAction(Request $request)
    {
        $produit = $this -> getDoctrine()
            -> getRepository(Produits::class)
            ->FindAll();

        $categorie = $this -> getDoctrine()
            -> getRepository(Categories::class)
            ->findAll();

        $rating = $this -> getDoctrine()
            -> getRepository(Produits::class)
            ->FindAll();

        /**
         * @var $paginator \Knp\Component\Pager\Paginator
         */
        $paginator = $this ->get('knp_paginator');
        $result=$paginator->paginate(
            $produit,
            $request->query->getInt('page',1),
            $request->query->getInt('limit',6)
        );



        //  $this->container->get('templating');

        $user = $this->getUser();
        //**************Nour PART *************************//
        $em = $this->getDoctrine()->getManager();
        $session = $request->getSession();
        //$session->clear();
        $nbr = count($session->get('panier'));
        if($nbr >= 1 )
            $produits = $em->getRepository('ProduitsBundle:Produits')->findBy(array('ref_p' => array_keys($session->get('panier'))));
        else $produits =array();
        //**************END Nour PART *************************//
        return $this -> render('@Produits/Produits/shop.html.twig', array('produit' => $result,'categorie' => $categorie ,'user' => $user,
            'rating' => $rating,
            'panier' =>$session->get('panier'),
            'produit1' => $produits));
    }

    public function filtrerCouleurAction(Request $request,$couleur)
    {
        $produit = $this -> getDoctrine()
            -> getRepository(Produits::class)
            ->findAll();

        $categorie = $this -> getDoctrine()
            -> getRepository(Categories::class)
            ->findAll();


        $user = $this->getUser();

        $arrayC=array();
        $i=0;

        foreach ($produit as $value){

            foreach ($value->getCouleurP() as $ac){

                if($ac == $couleur){
                    $arrayC[$i] = $value;
                    $i++;
                }
            }
        }

        /**
         * @var $paginator \Knp\Component\Pager\Paginator
         */
        $paginator = $this ->get('knp_paginator');
        $result=$paginator->paginate(
            $arrayC,
            $request->query->getInt('page',1),
            $request->query->getInt('limit',6)
        );

        //**************Nour PART *************************//
        $em = $this->getDoctrine()->getManager();
        $session = $request->getSession();
        //$session->clear();
        $nbr = count($session->get('panier'));
        if($nbr >= 1 )
            $produits = $em->getRepository('ProduitsBundle:Produits')->findBy(array('ref_p' => array_keys($session->get('panier'))));
        else $produits =array();
        //**************END Nour PART *************************//

        return $this -> render('@Produits/Produits/filtrer.html.twig', array('produit' => $result,'categorie' => $categorie ,'user' => $user,
            'panier' =>$session->get('panier'),
            'produit1' => $produits));
    }



    public function filtrerSexeAction(Request $request,$sexe)
    {
        $produit = $this -> getDoctrine()
            -> getRepository(Produits::class)
            ->FilterSexe($sexe);

        $categorie = $this -> getDoctrine()
            -> getRepository(Categories::class)
            ->findAll();

        /**
         * @var $paginator \Knp\Component\Pager\Paginator
         */
        $paginator = $this ->get('knp_paginator');
        $result=$paginator->paginate(
            $produit,
            $request->query->getInt('page',1),
            $request->query->getInt('limit',6)
        );



        //  $this->container->get('templating');

        $user = $this->getUser();
        //**************Nour PART *************************//
        $em = $this->getDoctrine()->getManager();
        $session = $request->getSession();
        //$session->clear();
        $nbr = count($session->get('panier'));
        if($nbr >= 1 )
            $produits = $em->getRepository('ProduitsBundle:Produits')->findBy(array('ref_p' => array_keys($session->get('panier'))));
        else $produits =array();
        //**************END Nour PART *************************//

        return $this -> render('@Produits/Produits/filtrer.html.twig', array('produit' => $result,'categorie' => $categorie ,'user' => $user,
            'panier' =>$session->get('panier'),
            'produit1' => $produits));
    }








    public function  alertAction(){
        return $this -> render('@Produits/Produits/alert.html.twig');
    }

    public function filtrerPrixAction(Request $request,$prix)
    {
        $produit = $this -> getDoctrine()
            -> getRepository(Produits::class)
            ->FilterPrix($prix);

        $categorie = $this -> getDoctrine()
            -> getRepository(Categories::class)
            ->findAll();

        /**
         * @var $paginator \Knp\Component\Pager\Paginator
         */
        $paginator = $this ->get('knp_paginator');
        $result=$paginator->paginate(
            $produit,
            $request->query->getInt('page',1),
            $request->query->getInt('limit',6)
        );



        //  $this->container->get('templating');

        $user = $this->getUser();

        //**************Nour PART *************************//
        $em = $this->getDoctrine()->getManager();
        $session = $request->getSession();
        //$session->clear();
        $nbr = count($session->get('panier'));
        if($nbr >= 1 )
            $produits = $em->getRepository('ProduitsBundle:Produits')->findBy(array('ref_p' => array_keys($session->get('panier'))));
        else $produits =array();
        //**************END Nour PART *************************//

        return $this -> render('@Produits/Produits/filtrer.html.twig', array('produit' => $result,'categorie' => $categorie ,'user' => $user,
            'panier' =>$session->get('panier'),
            'produit1' => $produits));
    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("/client/" , name="afficherProduits")
     *
     */

    public function afficherProduitsAction(Request $request)
    {
        $produit = $this -> getDoctrine()
            -> getRepository(Produits::class)
            ->FindAllProducts();

        $categorie = $this -> getDoctrine()
            -> getRepository(Categories::class)
            ->findAll();

        //  $this->container->get('templating');

        $user = $this->getUser();
        //**************Nour PART *************************//
        $em = $this->getDoctrine()->getManager();
        $session = $request->getSession();
        //$session->clear();
        $nbr = count($session->get('panier'));
        if($nbr >= 1 )
            $produits = $em->getRepository('ProduitsBundle:Produits')->findBy(array('ref_p' => array_keys($session->get('panier'))));
        else $produits =array();
        //**************END Nour PART *************************//

        return $this -> render('@Produits/Produits/afficherProduits.html.twig', array('produit' => $produit,'categorie' => $categorie ,'user' => $user,
            'panier' =>$session->get('panier'),
            'produit1' => $produits));
    }


    /**
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("/admin/")
     *
     * @Security("has_role('ROLES_ADMIN')")
     */

    public function ajouterCategorieAction(Request $request)
    {
        $categorie = new Categories();
        $form = $this -> createForm(CategoriesType::class, $categorie) -> handleRequest($request);
        $em = $this -> getDoctrine() -> getManager();
        $user = $this->getUser();

        if ($form -> isSubmitted() and $form -> isValid()) {
            $em -> persist($categorie);
            $em -> flush();

            return $this -> redirectToRoute('afficherCategories');

        }

        return $this -> render('@Produits/Produits/ajouterCategorie.html.twig',
            array('form' => $form -> createView(),'user' => $user));
    }

    /**
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Route("/admin/")
     *
     * @Security("has_role('ROLES_ADMIN')")
     */

    public function afficherCategoriesAction(Request $request)
    {
        $categorie = $this -> getDoctrine()
            -> getRepository(Categories::class)
            ->findAll();

        /**

Symfony/Baskel/src/Produits/ProduitsBundle/Resources/views/Produits/afficherProduitsBack.html.twig
{% extends 'default/back/header.html.twig' %}



{% block head %}
    {{ parent() }}
    <style>
        #div-cat-list{
            margin-left: 14%;
            margin-top: 5%;
            width: 84%;

        }
        #edit-cat, #add-solde{
            padding: 6px 10px;
            font-size: 12px;
            border-radius: 3px;
            border: 1px solid rgba(0,0,0,.12);
            background: #152036;
            display: inline-block;

            color: whitesmoke;
        }

        #delete-cat{
            background:none;
            border: none;
            font-size: 12px;
            color: whitesmoke;
        }


        #add-cat-link {
            background: #fd4339;
            border-color: #fd4339;

        }


        table tr:nth-child(odd){
            background-color: #2d4c7d;

        }

        #myTable{
            height: 80%;
        }


    </style>
    <script>
        window.onload = function() {

            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                title: {
                    text: "Produits en stock/hors stock"
                },
                data: [{
                    type: "pie",
                    startAngle: 240,
                    yValueFormatString: "##0.00'%'",
                    indexLabel: "{label} {y}",
                    dataPoints: [
                        {y: {{ prodExp }}, label: "Repture de stock"},
                        {y: {{ prodNonExp }}, label: "En stock"},

                    ]
                }]
            });
            chart.render();

        }
    </script>






{% endblock %}

{% block container %}





    <div class="product-status mg-b-30">



        <div class="container-fluid">

            <script src="{{ asset('jquery-3.4.1.min.js')}}"> </script>
            <script>
                $(document).ready(function(){
                    $("#myInput").on("keyup", function() {
                        var value = $(this).val().toLowerCase();
                        $("#myTable tr").filter(function() {
                            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                        });
                    });
                });
            </script>


            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

            <script type="text/javascript">
                google.charts.load("current", {packages:["corechart"]});
                google.charts.setOnLoadCallback(drawChart);
                function drawChart() {
                    var data = google.visualization.arrayToDataTable([
                        ['Task', 'Hours per Day'],
                        ['Produits en stock',     {{ prodNonExp }} ],
                        ['Produits Hors stock',      {{ prodExp }}],
                    ]);

                    var options = {
                        title: 'Produits En Stock/ Hors Stock.',
                        backgroundColor: '#2d4c7d',
                        is3D: true,
                    };

                    var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
                    chart.draw(data, options);
                }
            </script>


            <div class="row">

                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div id="piechart_3d" style="width: 555px; height: 195px; margin-left: 16.5%; margin-top: 2%; margin-bottom: -2%;" ></div>
                    <div class="product-status-wrap" id="div-cat-list">

                        <h4>Liste Des Produits</h4>



                        <div class="add-product">
                            <a href="{{ path('ajouterProduit') }}" id="add-cat-link">+ Un Produit</a>
                        </div>
                        <table id="myTable">
                            <tr style="background-color: #101829">

                                <th></th>
                                <th>Image</th>

                                <th >Référence</th>

                                <th>Nom Produit</th>

                                <th>Genre</th>

                                <th style="width: 7%;">Couleurs</th>

                                <th>Quantité</th>

                                <th>Prix</th>

                                <th>Promotion</th>

                                <th>Marque</th>

                                <th>Catégorie associée</th>

                                <th>Description</th>

                                <th>Stock</th>





                                <th style="width: 8%;"></th>
                            </tr>


                            {% for c in produits %}

                                <tr>
                                    <td><a data-toggle="tooltip" title="Trash" class="pd-setting-ed" id="delete-cat" href="{{ path('supprimerProduit', { 'ref_p': c.refP }) }}"><i class="fa fa-times" aria-hidden="true"></i></a></td>
                                    <td> <img src="{{ asset('uploads/images/' ~ c.image) }}" alt="product 1"  style="width: 50px; height: 50px;"/></td>
                                    <td>{{ c.refP }}</td>
                                    <td>{{ c.nomP }}</td>
                                    <td >{{ c.genreP }}</td>
                                    <td> {% for clr in c.couleurP %}
                                            * {{ clr }} <br>
                                        {% endfor %} </td>
                                    <td >{{ c.quantiteP }}</td>
                                    <td>{{ c.prixP }}</td>
                                    <td>{{ c.solde }}%</td>
                                    <td >{{ c.marqueP }}</td>
                                    <td>{{ c.refC.libelle }}</td>
                                    <td>{{ c.description }}</td>
                                    <td>{% if c.quantiteP == 0 %}
                                            <label style=" background-color: #FD4339; border-radius: 5px; padding: 5px 5px 5px 5px;">Rupture de stock</label>
                                        {% else %}
                                            <label style=" background-color: #5e7ee1; border-radius: 5px; padding: 5px 5px 5px 5px; ">En stock</label>
                                        {% endif %}
                                    </td>

                                    <td>
                                        <a data-toggle="tooltip" title="Edit" class="pd-setting-ed" id="edit-cat" href="{{ path('modifierProduit', { 'ref_p': c.refP }) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>

                                        <a data-toggle="tooltip" title="solde" class="pd-setting-ed" id="add-solde" href="{{ path('soldeEdit', { 'ref_p': c.refP }) }}"><i class="fa fa-percent" aria-hidden="true"></i></a>
                                    </td>




                                </tr>
                            {% endfor %}

                        </table>
                        <div class="custom-pagination">
                            {# display navigation #}
                            <div class="navigation">
                                {{ knp_pagination_render(produits) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

Symfony/Baskel/src/Produits/ProduitsBundle/Resources/views/Produits/alert.html.twig
{% extends 'default/front/header.html.twig' %}

    {% block container  %}

        <!--Start section large top for tabs content-->
        <div class="section-large-top">
            <div class="container" style="margin-bottom: 1000px;margin-top: 10%;margin-left: 40%">




                    <h3>Désole! Ce produit est déjà ajouté à votre wishlist.</h3>




            </div>

        </div>

    {% endblock %}

Symfony/Baskel/src/Produits/ProduitsBundle/Resources/views/Produits/rechercherProdBack.html.twig
{% extends 'default/back/header.html.twig' %}



{% block head %}
    {{ parent() }}
    <style>
        #div-cat-list{
            margin-left: 16.5%;
            margin-top: 5%;
            width: 84%;

        }
        #delete-cat ,#edit-cat{
            padding: 5px 10px;
            font-size: 14px;
            border-radius: 3px;
            border: 1px solid rgba(0,0,0,.12);
            background: #152036;
            display: inline-block;
            margin-right: 5px;
            color: whitesmoke;
        }
        #add-cat-link {
            background: #fd4339;
            border-color: #fd4339;
        }



    </style>
{% endblock %}

{% block container %}





    <div class="product-status mg-b-30">



        <div class="container-fluid">
            {{ form_start(form) }}
            <table>
                <tr>
                    <td>Référence:</td>
                    <td>{{ form_widget(form.refP) }}</td>
                </tr>
                <tr>
                    <td>{{ form_widget(form.rechercher) }}</td>
                </tr>
            </table>
            {{ form_end(form) }}
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="product-status-wrap" id="div-cat-list">

                        <h4>Liste Des Catégories</h4>
                        <div class="add-product">
                            <a href="{{ path('ajouterProduit') }}" id="add-cat-link">+ Un Produit</a>
                        </div>
                        <table >
                            <tr>

                                <th>Image</th>

                                <th >Référence</th>

                                <th>Nom Produit</th>

                                <th>Genre</th>

                                <th>Couleurs</th>

                                <th>Quantité</th>

                                <th>Prix</th>

                                <th>Marque</th>

                                <th>Catégorie associée</th>

                                <th>Description</th>

                                <th>Stock</th>



                                <th style="width: 9%"></th>
                            </tr>


                            {% for c in form %}
                                <tr>
                                    <td> <img src="{{ asset('uploads/images/' ~ c.image) }}" alt="product 1"  style="width: 50px; height: 50px;"/></td>
                                    <td>{{ c.refP }}</td>
                                    <td>{{ c.nomP }}</td>
                                    <td>{{ c.genreP }}</td>
                                    <td>[ {% for clr in c.couleurP %}
                                            {{ clr }} ,
                                        {% endfor %} ]</td>
                                    <td>{{ c.quantiteP }}</td>
                                    <td>{{ c.prixP }}</td>
                                    <td>{{ c.marqueP }}</td>
                                    <td>{{ c.refC.libelle }}</td>
                                    <td>{{ c.description }}</td>
                                    <td>{% if c.quantiteP == 0 %}
                                            <label style=" background-color: #FD4339; border-radius: 5px; padding: 5px 5px 5px 5px;">Rupture de stock</label>
                                        {% else %}
                                            <label style=" background-color: #5e7ee1; border-radius: 5px; padding: 5px 5px 5px 5px; ">En stock</label>
                                        {% endif %}
                                    </td>

                                    <td>
                                        <a data-toggle="tooltip" title="Edit" class="pd-setting-ed" id="edit-cat" href="{{ path('modifierProduit', { 'ref_p': c.refP }) }}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                                        <a data-toggle="tooltip" title="Trash" class="pd-setting-ed" id="delete-cat" href="{{ path('supprimerProduit', { 'ref_p': c.refP }) }}"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                                    </td>



                                </tr>
                            {% endfor %}

                        </table>
                        <div class="custom-pagination">
                            <ul class="pagination">
                                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                                <li class="page-item"><a class="page-link" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}